/***********************************************************************/
/*                                                                     */
/*  FILE        :sbrk.h                                                */
/*  DATE        :Sun, Nov 15, 2009                                     */
/*  DESCRIPTION :Header file of sbrk file                              */
/*  CPU TYPE    :H8SX/1658                                             */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
/* size of area managed by sbrk */
#define HEAPSIZE 0x420
